Languages:  #language name will be used to create namespace
  - English
  - Chinese
  - Japanese
# Font, need to provide id from System_Font_List.txt or just name
Fonts:
  - Name: Maintext
    TTF-Num: 752    # Do NOT use TTF-Num and TTF-Name t same time
    Size: 25
    # ExtraBlock: 0x0021, 0x007E, 0x00AB, 0x00FF # 2 is a pair. Always write in pairs!
  - Name: Bigtext
    TTF-Num: 752    # Do NOT use TTF-Num and TTF-Name t same time
    Size: 55
    # Note: Files are generated according to their system name and size
    #       So, DO NOT use different names if they have same TTF-Num/TTF-Name and size

  # - Name: icon
  #   TTF-Num: 176
  #   # TTF-Name: Material Icons
  #   Size: 40
  - Name: icon-25
    TTF-Num: 176
    # TTF-Name: Material cons
    Size: 25

Strings:
  # - Name: Hello
  #   Content-Chinese: 
  #     Font: Maintext
  #     Value: 你好
  #   Content-English: 
  #     Font: Maintext
  #     Value: "Hello"
  #   Content-Japanese: 
  #     Font: Maintext
  #     Value: こんにちは

  # - Name: EnglishString
  #   Content-all:
  #     Font: Maintext
  #     Value: This is an English String
  # - Name: EnglishStringButChinese
  #   Content-all:    # Content-all, all languages
  #     Font: Maintext
  #     Value: This is an English String
  #   Content-Chinese:  # over-write in specific language
  #     Font: Maintext
  #     Value: Except Chinese!
  # - Name: Smile
  #   Middle: true
  #   Content-all:
  #     Font: icon
  #     Value: "\ue7f2" # TODO, hex value
  # - Name: RadioButtonEmpty
  #   Content-all:
  #    Font: icon-25
  #    Value: "\ue836"
  - Name: FingerPrint
    Content-all:
     Font: icon-25
     Value: "\ue90d"
  # - Name: fuck
  #   Content-all: 
  #     Font: Maintext
  #     Value: 阿卜·日·法拉兹曾经说过，学问是异常珍贵的东西
  - Name: LanguageName
    Content-English:
      Font: Maintext
      Value: English
    Content-Chinese:
      Font: Maintext
      Value: 简体中文
    Content-Japanese:
      Font: Bigtext
      Value: 日本語





# Languages:  #language name will be used to create namespace
#   - English
#   - Chinese
#   - Japanese
# # Font, need to provide id from System_Font_List.txt or just name
# Fonts:
#   # - Name: text
#   #   TTF-Name: "Final-Frontier"    # Do NOT use TTF-Num and TTF-Name t same time
#   #     Type: ttf                   # ttf or otf
#   #   Size: 15
#   - Name: Maintext
#     TTF-Num: 752    # Do NOT use TTF-Num and TTF-Name t same time
#     Size: 25
#     # ExtraBlock: 0x0021, 0x007E, 0x00AB, 0x00FF # 2 is a pair. Always write in pairs!
#   - Name: Bigtext
#     TTF-Num: 752    # Do NOT use TTF-Num and TTF-Name t same time
#     Size: 55
#     # Note: Files are generated according to their system name and size
#     #       So, DO NOT use different names if they have same TTF-Num/TTF-Name and size

#   - Name: icon
#     TTF-Num: 176
#     # TTF-Name: Material Icons
#     Size: 40
#   - Name: icon-25
#     TTF-Num: 176
#     # TTF-Name: Material cons
#     Size: 25

# Strings:
#   - Name: Hello
#     Content-Chinese: 
#       Font: Maintext
#       Value: 你好
#     Content-English: 
#       Font: Maintext
#       Value: "Hello"
#     Content-Japanese: 
#       Font: Maintext
#       Value: こんにちは

#   - Name: EnglishString
#     Content-all:
#       Font: Maintext
#       Value: This is an English String
#   - Name: EnglishStringButChinese
#     Content-all:    # Content-all, all languages
#       Font: Maintext
#       Value: This is an English String
#     Content-Chinese:  # over-write in specific language
#       Font: Maintext
#       Value: Except Chinese!
#   - Name: Smile
#     Middle: true
#     Content-all:
#       Font: icon
#       Value: "\ue7f2"
#   - Name: RadioButtonEmpty
#     Content-all:
#      Font: icon-25
#      Value: "\ue836"
#   - Name: RadioButtonFilled
#     Content-all:
#      Font: icon-25
#      Value: "\ue837"
#   - Name: fuck
#     Content-all: 
#       Font: Maintext
#       Value: 阿卜·日·法拉兹曾经说过，学问是异常珍贵的东西
#   - Name: LanguageName
#     Content-English:
#       Font: Maintext
#       Value: English
#     Content-Chinese:
#       Font: Maintext
#       Value: 简体中文
#     Content-Japanese:
#       Font: Bigtext
#       Value: 日本語