Languages:  #language name will be used to create namespace
  - English
# Font, need to provide id from System_Font_List.txt or just name
Fonts:
  - Name: Maintext
    TTF-Num: 752    # Do NOT use TTF-Num and TTF-Name t same time
    Size: 25

Strings:
  - Name: BattleWolf
    Content-all:
     Font: Maintext
     Value: "战狼"
